app:
  name: "Tray Pumpkin"
  tooltip: "Pumpkin tray utility"
  icon: "assets/pumpkin-green.png"
  cmd: "notify-send 'APP STARTED'"

left_click:
  cmd: "notify-send 'Click Start'"
  icon: "assets/pumpkin-orange.png"

left_click_toggle:
  cmd: "notify-send 'Click Toggle'"
  icon: "assets/pumpkin-green.png"

quit:
  cmd: "notify-send 'QUIT'"

menu:
  - name: "Edit config.yaml"
    cmd: "gedit config.yaml"

  - separator: true

  - name: "Start MyApp-1"
    cmd: "notify-send 'Start'"
    icon: "assets/pumpkin-orange.png"

  - name: "Stop MyApp-1"
    cmd: "notify-send 'Stop'"
    icon: "assets/pumpkin-line.png"

  - separator: true

  - name: "Restart App-2"
    cmd: "notify-send 'Hello world'"

  - separator: true

  - name: "Penguins Big"
    cmd: "xpenguins --theme 'Big Penguins' -a -b"
    icon: "assets/tux.png"

  - name: "Penguins Start"
    cmd: "xpenguins --theme Penguins -a -b"
    icon: "assets/tux.png"

  - name: "Penguins Squish"
    cmd: "xpenguins --theme Penguins -a -b -s"
    icon: "assets/tux.png"

  - name: "Penguins Stop"
    cmd: "killall xpenguins"
    icon: "assets/pumpkin-green.png"

